# Generated by Django 2.1.7 on 2019-02-26 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseorg',
            name='category',
            field=models.CharField(choices=[('pxjg', '培训机构'), ('gr', '个人'), ('gx', '高校')], default='培训机构', max_length=20, verbose_name='机构类别'),
        ),
    ]
