# Generated by Django 2.1.7 on 2019-03-04 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0007_courseorg_age'),
        ('organization', '0006_auto_20190228_2211'),
    ]

    operations = [
    ]
