# Generated by Django 2.1.7 on 2019-03-04 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_auto_20190228_2211'),
        ('courses', '0009_auto_20190301_1006'),
    ]

    operations = [
    ]
